config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :jobs
  resources :periods
  resources :job_job_associations
  resources :event_job_period_associations

  resources :users
  resources :microposts, only: [:create, :destroy]

  root 'static_pages#home'
  get 'home'       => 'static_pages#home'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'impressum'  => 'static_pages#impressum'
  get 'tcpsp'      => 'static_pages#tcpsp'

  get  'signup'    => 'users#new'

  get   'login'    => 'sessions#new'
  post    'login'  => 'sessions#create'
  post   'logout'  => 'sessions#destroy'
  delete 'logout'  => 'sessions#destroy'

  post "periods/change", as: :change_periods

  get 'sessions/new'
  get 'users/new'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def support
  end

  def about
  end

  def contact
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "Über uns") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | EvenTraum</title>
  </head>
  <body>
  <h1>Über die Gründer</h1>
  <br>
  <p>Xelat Akcam</p>

  <div style=><%=image_tag("Hayat.jpg", width: "140", height: "200")%></div>
  <p>Hayat Boulakhrif</p>

  <div style=><%=image_tag("Nadia.jpg", width: "150", height: "200")%></div>
  <p>Nadia Kruszewski</p>

  <h1>Über das Unternehmen</h1>
  <p>Im Rahmen der Veranstaltung „Entwicklung von Anwendungssystemen“
    am <a href="http://www.prod.uni-hannover.de">Institut für Produktionswirtschaft</a> im Master „Operations Management and Research“
    an der Gottfried Wilhelm Leibniz Universität Hannover ist die Web-Applikation „EvenTraum“ entwickelt worden.<br>
    Die Web-Applikation basiert auf dem Ruby on Rails Tutorial – Learn Web Development with Rails von Michael Hartl.<br>
    Mit der Web-Applikation „EvenTraum“ kann ein Multi-Projekt-Planungsproblem gelöst werden.
  </p>
  <br>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Kontakt") %>
<!DOCTYPE html>
<html>

  <head>
    <title><%= yield(:title) %> | EvenTraum</title>
  </head>
  <body>
  <h1>Kontakt</h1>
  <br>
  <p>Kontaktieren Sie bei Rückfragen oder Anregungen gerne das EvenTraum-Team.
  <br><br>
  Xelat Akcam
  <div style="text-align:left"><%=image_tag("email.jpg", size: "20") + "  xelat.akcam@gmail.com" %></div>
  <br>
  <p>Hayat Boulakhrif</p>
  <div style="text-align:left"><%=image_tag("email.jpg", size: "20") + "  ha.boulakhrif@web.de" %></div>
  <br>
  <p>Nadia Kruszewski</p>
  <div style="text-align:left"><%=image_tag("email.jpg", size: "20") + "  nadiakruszewski@yahoo.de" %></div>
  </p>
  </body>

</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Startseite") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | EvenTraum </title>
</head>
<ul class="bxslider">
  <div style="text-align:center"><%=image_tag("Image_0.png") %></div>
  <div style="text-align:center"><%=image_tag("Image_1.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_3.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_5.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_6.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_7.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_8.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_9.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_10.jpg") %></div>
  <div style="text-align:center"><%=image_tag("Image_12.jpg") %></div>
</ul>
<p><a href="" id="reload-slider">Click to reload slider with new settings</a></p>
</html>

app/views/static_pages/impressum.html.erb
<% provide(:title, "Impressum") %>
<!DOCTYPE html>
<html>

  <head>
    <title><%= yield(:title) %> | EvenTraum</title>
  </head>
  <body>

  <h1>Impressum</h1>

  <a>
    EvenTraum GmbH<br>
    c/o Leibniz Universität Hannover<br>
    Institut für Produktionswirtschaft<br>
    Königsworther Platz 1<br>
    D-30167 Hannover<br>
    Email: eventraum@gmail.com<br><br>
    Vertretungsberichtsberechtigter Vorstand:<br>
    Xelat Akcam<br>
    Hayat Boulakhrif<br>
    Nadia Kruszewski
  </a>

  </body>

</html>

app/views/static_pages/tcpsp.html.erb
<% provide(:title, 'Eventplanung') %>
<h1>Eventplanung</h1>
<p>
  Hier können Sie die Daten der Multi-Projekt-Planung verwalten  <br><br>

  <%= link_to "Hier geht es zur Verwaltung der Vorgänge!", jobs_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Events!", events_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Perioden!", periods_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Vorgänger-Nachfolger-Beziehungen!", job_job_associations_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Events-Vorgänge-Perioden-Zuordnungen!", event_job_period_associations_path %><br>

</p>

<br>

<% if logged_in? %>


<% end %>
