config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :jobs
  resources :periods
  resources :job_job_associations
  resources :event_job_period_associations

  resources :users
  resources :microposts, only: [:create, :destroy]

  root 'static_pages#home'
  get 'home'       => 'static_pages#home'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'impressum'  => 'static_pages#impressum'
  get 'tcpsp'      => 'static_pages#tcpsp'

  get  'signup'    => 'users#new'

  get   'login'    => 'sessions#new'
  post    'login'  => 'sessions#create'
  post   'logout'  => 'sessions#destroy'
  delete 'logout'  => 'sessions#destroy'

  post "periods/change", as: :change_periods

  get 'sessions/new'
  get 'users/new'

end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :job_job_associations, foreign_key: "successor_id", :dependent => :destroy
  has_many :reverse_job_associations, foreign_key: "predecessor_id", class_name: "JobJobAssociation", :dependent => :destroy
  has_many :successors, through: :job_job_associations, source: :successor_id
  has_many :predecessors, through: :reverse_job_associations, source: :predecessor_id
  has_many :events, through: :event_job_period_associations
  has_many :periods, through: :event_job_period_associations

end


#def ressource_demand
#  if ressource_demand < 0.integer
#    errors.add(:integer, "should be greater than or equal to 0")
#  end


#class Job < ApplicationRecord
#validates :points, numericality: true
#validates :ressource_demand, numericality: { greater_than: 0 }
#end


#integer_field_tag 'ressource_demand', nil, min: 1
# => <input id="quantity" name="quantity" min="1" type="number" />

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Der Vorgang wurde erfolgreich angelegt.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Der Vorgang wurde erfolgreich aktualisiert.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Der Vorgang wurde entfernt.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :processing_time, :ressources_demand)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Vorgang' %><br>
    <%= f.collection_select(:id, Job.all,:id,:name) %>
  </div>

  <div class="field">
    <%= f.label 'Vorgangsdauer' %><br>
    <%= f.text_field :processing_time, type: "number", min:0, max:3, required: "required" %>
  </div>
  <div class="field">
    <%= f.label 'Ressourcenbedarf' %><br>
    <%= f.number_field :ressources_demand, type: "number", min:1, max:3, required: "required" %>
  </div>
  <div class="actions">
    <%= f.submit 'Neuen Vorgang anlegen' %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Vorgänge aktualisieren</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @job %> |
<%= link_to 'Zurück', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Übersicht der Vorgänge</h1>

<table id="jobs" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Vorgangsdauer in Wochen</th>
      <th>Ressourcenbedarf</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.name %></td>
        <td><%= job.processing_time %></td>
        <td><%= job.ressources_demand %></td>
        <td><%= link_to 'Anzeigen', job %></td>
        <td><%= link_to 'Ändern', edit_job_path(job) %></td>
        <td><%= link_to 'Löschen', job, method: :delete, data: { confirm: 'Möchten Sie diesen Eintrag sicher löschen?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neuer Vorgang', new_job_path %>
<br>  <br><%= link_to 'Zurück zur Eventplanung', tcpsp_path %>

app/views/jobs/new.html.erb
<h1>Neuer Vorgang</h1>

<%= render 'form' %>

<%= link_to 'Zurück', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= best_in_place @job, :name %>
</p>

<p>
  <strong>Vorgangsdauer in Wochen:</strong>
  <%= best_in_place @job, :processing_time %>
</p>

<p>
  <strong>Ressourcenbedarf:</strong>
  <%= best_in_place @job, :ressources_demand %>
</p>

<%= link_to 'Ändern', edit_job_path(@job) %> |
<%= link_to 'Zurück', jobs_path %>